import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fisrt Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="flex flex-wrap justify-center m-5">{children}</main>
      </body>
    </html>
  );
}
